// This file is generated by rust-protobuf 2.2.0. Do not edit
// @generated

// https://github.com/Manishearth/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy)]

#![cfg_attr(rustfmt, rustfmt_skip)]

#![allow(box_pointers)]
#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unsafe_code)]
#![allow(unused_imports)]
#![allow(unused_results)]

use protobuf::Message as Message_imported_for_functions;
use protobuf::ProtobufEnum as ProtobufEnum_imported_for_functions;

#[derive(PartialEq,Clone,Default)]
pub struct KvReq {
    // message fields
    pub key: ::std::string::String,
    pub value: ::std::string::String,
    pub client_id: u64,
    pub seq: u64,
    pub req_type: ReqType,
    pub peer_id: u64,
    pub peer_addr: ::std::string::String,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl KvReq {
    pub fn new() -> KvReq {
        ::std::default::Default::default()
    }

    // string key = 1;

    pub fn clear_key(&mut self) {
        self.key.clear();
    }

    // Param is passed by value, moved
    pub fn set_key(&mut self, v: ::std::string::String) {
        self.key = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_key(&mut self) -> &mut ::std::string::String {
        &mut self.key
    }

    // Take field
    pub fn take_key(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.key, ::std::string::String::new())
    }

    pub fn get_key(&self) -> &str {
        &self.key
    }

    // string value = 2;

    pub fn clear_value(&mut self) {
        self.value.clear();
    }

    // Param is passed by value, moved
    pub fn set_value(&mut self, v: ::std::string::String) {
        self.value = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_value(&mut self) -> &mut ::std::string::String {
        &mut self.value
    }

    // Take field
    pub fn take_value(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.value, ::std::string::String::new())
    }

    pub fn get_value(&self) -> &str {
        &self.value
    }

    // uint64 client_id = 3;

    pub fn clear_client_id(&mut self) {
        self.client_id = 0;
    }

    // Param is passed by value, moved
    pub fn set_client_id(&mut self, v: u64) {
        self.client_id = v;
    }

    pub fn get_client_id(&self) -> u64 {
        self.client_id
    }

    // uint64 seq = 4;

    pub fn clear_seq(&mut self) {
        self.seq = 0;
    }

    // Param is passed by value, moved
    pub fn set_seq(&mut self, v: u64) {
        self.seq = v;
    }

    pub fn get_seq(&self) -> u64 {
        self.seq
    }

    // .kvrpcpb.ReqType req_type = 5;

    pub fn clear_req_type(&mut self) {
        self.req_type = ReqType::Get;
    }

    // Param is passed by value, moved
    pub fn set_req_type(&mut self, v: ReqType) {
        self.req_type = v;
    }

    pub fn get_req_type(&self) -> ReqType {
        self.req_type
    }

    // uint64 peer_id = 6;

    pub fn clear_peer_id(&mut self) {
        self.peer_id = 0;
    }

    // Param is passed by value, moved
    pub fn set_peer_id(&mut self, v: u64) {
        self.peer_id = v;
    }

    pub fn get_peer_id(&self) -> u64 {
        self.peer_id
    }

    // string peer_addr = 7;

    pub fn clear_peer_addr(&mut self) {
        self.peer_addr.clear();
    }

    // Param is passed by value, moved
    pub fn set_peer_addr(&mut self, v: ::std::string::String) {
        self.peer_addr = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_peer_addr(&mut self) -> &mut ::std::string::String {
        &mut self.peer_addr
    }

    // Take field
    pub fn take_peer_addr(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.peer_addr, ::std::string::String::new())
    }

    pub fn get_peer_addr(&self) -> &str {
        &self.peer_addr
    }
}

impl ::protobuf::Message for KvReq {
    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.key)?;
                },
                2 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.value)?;
                },
                3 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_uint64()?;
                    self.client_id = tmp;
                },
                4 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_uint64()?;
                    self.seq = tmp;
                },
                5 => {
                    if wire_type == ::protobuf::wire_format::WireTypeVarint {self.req_type = is.read_enum()?;} else { return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type)); }
                },
                6 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_uint64()?;
                    self.peer_id = tmp;
                },
                7 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.peer_addr)?;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if !self.key.is_empty() {
            my_size += ::protobuf::rt::string_size(1, &self.key);
        }
        if !self.value.is_empty() {
            my_size += ::protobuf::rt::string_size(2, &self.value);
        }
        if self.client_id != 0 {
            my_size += ::protobuf::rt::value_size(3, self.client_id, ::protobuf::wire_format::WireTypeVarint);
        }
        if self.seq != 0 {
            my_size += ::protobuf::rt::value_size(4, self.seq, ::protobuf::wire_format::WireTypeVarint);
        }
        if self.req_type != ReqType::Get {
            my_size += ::protobuf::rt::enum_size(5, self.req_type);
        }
        if self.peer_id != 0 {
            my_size += ::protobuf::rt::value_size(6, self.peer_id, ::protobuf::wire_format::WireTypeVarint);
        }
        if !self.peer_addr.is_empty() {
            my_size += ::protobuf::rt::string_size(7, &self.peer_addr);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream) -> ::protobuf::ProtobufResult<()> {
        if !self.key.is_empty() {
            os.write_string(1, &self.key)?;
        }
        if !self.value.is_empty() {
            os.write_string(2, &self.value)?;
        }
        if self.client_id != 0 {
            os.write_uint64(3, self.client_id)?;
        }
        if self.seq != 0 {
            os.write_uint64(4, self.seq)?;
        }
        if self.req_type != ReqType::Get {
            os.write_enum(5, self.req_type.value())?;
        }
        if self.peer_id != 0 {
            os.write_uint64(6, self.peer_id)?;
        }
        if !self.peer_addr.is_empty() {
            os.write_string(7, &self.peer_addr)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &::std::any::Any {
        self as &::std::any::Any
    }
    fn as_any_mut(&mut self) -> &mut ::std::any::Any {
        self as &mut ::std::any::Any
    }
    fn into_any(self: Box<Self>) -> ::std::boxed::Box<::std::any::Any> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> KvReq {
        KvReq::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static mut descriptor: ::protobuf::lazy::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const ::protobuf::reflect::MessageDescriptor,
        };
        unsafe {
            descriptor.get(|| {
                let mut fields = ::std::vec::Vec::new();
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                    "key",
                    |m: &KvReq| { &m.key },
                    |m: &mut KvReq| { &mut m.key },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                    "value",
                    |m: &KvReq| { &m.value },
                    |m: &mut KvReq| { &mut m.value },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeUint64>(
                    "client_id",
                    |m: &KvReq| { &m.client_id },
                    |m: &mut KvReq| { &mut m.client_id },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeUint64>(
                    "seq",
                    |m: &KvReq| { &m.seq },
                    |m: &mut KvReq| { &mut m.seq },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeEnum<ReqType>>(
                    "req_type",
                    |m: &KvReq| { &m.req_type },
                    |m: &mut KvReq| { &mut m.req_type },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeUint64>(
                    "peer_id",
                    |m: &KvReq| { &m.peer_id },
                    |m: &mut KvReq| { &mut m.peer_id },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                    "peer_addr",
                    |m: &KvReq| { &m.peer_addr },
                    |m: &mut KvReq| { &mut m.peer_addr },
                ));
                ::protobuf::reflect::MessageDescriptor::new::<KvReq>(
                    "KvReq",
                    fields,
                    file_descriptor_proto()
                )
            })
        }
    }

    fn default_instance() -> &'static KvReq {
        static mut instance: ::protobuf::lazy::Lazy<KvReq> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const KvReq,
        };
        unsafe {
            instance.get(KvReq::new)
        }
    }
}

impl ::protobuf::Clear for KvReq {
    fn clear(&mut self) {
        self.clear_key();
        self.clear_value();
        self.clear_client_id();
        self.clear_seq();
        self.clear_req_type();
        self.clear_peer_id();
        self.clear_peer_addr();
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for KvReq {
    fn fmt(&self, f: &mut ::std::fmt::Formatter) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for KvReq {
    fn as_ref(&self) -> ::protobuf::reflect::ProtobufValueRef {
        ::protobuf::reflect::ProtobufValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
pub struct ConfChangeReq {
    // message fields
    pub cc: ::protobuf::SingularPtrField<super::eraftpb::ConfChange>,
    pub ip: ::std::string::String,
    pub port: u32,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl ConfChangeReq {
    pub fn new() -> ConfChangeReq {
        ::std::default::Default::default()
    }

    // .eraftpb.ConfChange cc = 1;

    pub fn clear_cc(&mut self) {
        self.cc.clear();
    }

    pub fn has_cc(&self) -> bool {
        self.cc.is_some()
    }

    // Param is passed by value, moved
    pub fn set_cc(&mut self, v: super::eraftpb::ConfChange) {
        self.cc = ::protobuf::SingularPtrField::some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_cc(&mut self) -> &mut super::eraftpb::ConfChange {
        if self.cc.is_none() {
            self.cc.set_default();
        }
        self.cc.as_mut().unwrap()
    }

    // Take field
    pub fn take_cc(&mut self) -> super::eraftpb::ConfChange {
        self.cc.take().unwrap_or_else(|| super::eraftpb::ConfChange::new())
    }

    pub fn get_cc(&self) -> &super::eraftpb::ConfChange {
        self.cc.as_ref().unwrap_or_else(|| super::eraftpb::ConfChange::default_instance())
    }

    // string ip = 2;

    pub fn clear_ip(&mut self) {
        self.ip.clear();
    }

    // Param is passed by value, moved
    pub fn set_ip(&mut self, v: ::std::string::String) {
        self.ip = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_ip(&mut self) -> &mut ::std::string::String {
        &mut self.ip
    }

    // Take field
    pub fn take_ip(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.ip, ::std::string::String::new())
    }

    pub fn get_ip(&self) -> &str {
        &self.ip
    }

    // uint32 port = 3;

    pub fn clear_port(&mut self) {
        self.port = 0;
    }

    // Param is passed by value, moved
    pub fn set_port(&mut self, v: u32) {
        self.port = v;
    }

    pub fn get_port(&self) -> u32 {
        self.port
    }
}

impl ::protobuf::Message for ConfChangeReq {
    fn is_initialized(&self) -> bool {
        for v in &self.cc {
            if !v.is_initialized() {
                return false;
            }
        };
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_singular_message_into(wire_type, is, &mut self.cc)?;
                },
                2 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.ip)?;
                },
                3 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_uint32()?;
                    self.port = tmp;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if let Some(ref v) = self.cc.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
        }
        if !self.ip.is_empty() {
            my_size += ::protobuf::rt::string_size(2, &self.ip);
        }
        if self.port != 0 {
            my_size += ::protobuf::rt::value_size(3, self.port, ::protobuf::wire_format::WireTypeVarint);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream) -> ::protobuf::ProtobufResult<()> {
        if let Some(ref v) = self.cc.as_ref() {
            os.write_tag(1, ::protobuf::wire_format::WireTypeLengthDelimited)?;
            os.write_raw_varint32(v.get_cached_size())?;
            v.write_to_with_cached_sizes(os)?;
        }
        if !self.ip.is_empty() {
            os.write_string(2, &self.ip)?;
        }
        if self.port != 0 {
            os.write_uint32(3, self.port)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &::std::any::Any {
        self as &::std::any::Any
    }
    fn as_any_mut(&mut self) -> &mut ::std::any::Any {
        self as &mut ::std::any::Any
    }
    fn into_any(self: Box<Self>) -> ::std::boxed::Box<::std::any::Any> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> ConfChangeReq {
        ConfChangeReq::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static mut descriptor: ::protobuf::lazy::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const ::protobuf::reflect::MessageDescriptor,
        };
        unsafe {
            descriptor.get(|| {
                let mut fields = ::std::vec::Vec::new();
                fields.push(::protobuf::reflect::accessor::make_singular_ptr_field_accessor::<_, ::protobuf::types::ProtobufTypeMessage<super::eraftpb::ConfChange>>(
                    "cc",
                    |m: &ConfChangeReq| { &m.cc },
                    |m: &mut ConfChangeReq| { &mut m.cc },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                    "ip",
                    |m: &ConfChangeReq| { &m.ip },
                    |m: &mut ConfChangeReq| { &mut m.ip },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeUint32>(
                    "port",
                    |m: &ConfChangeReq| { &m.port },
                    |m: &mut ConfChangeReq| { &mut m.port },
                ));
                ::protobuf::reflect::MessageDescriptor::new::<ConfChangeReq>(
                    "ConfChangeReq",
                    fields,
                    file_descriptor_proto()
                )
            })
        }
    }

    fn default_instance() -> &'static ConfChangeReq {
        static mut instance: ::protobuf::lazy::Lazy<ConfChangeReq> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const ConfChangeReq,
        };
        unsafe {
            instance.get(ConfChangeReq::new)
        }
    }
}

impl ::protobuf::Clear for ConfChangeReq {
    fn clear(&mut self) {
        self.clear_cc();
        self.clear_ip();
        self.clear_port();
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for ConfChangeReq {
    fn fmt(&self, f: &mut ::std::fmt::Formatter) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for ConfChangeReq {
    fn as_ref(&self) -> ::protobuf::reflect::ProtobufValueRef {
        ::protobuf::reflect::ProtobufValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
pub struct GetResp {
    // message fields
    pub value: ::std::string::String,
    pub err: RespErr,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl GetResp {
    pub fn new() -> GetResp {
        ::std::default::Default::default()
    }

    // string value = 1;

    pub fn clear_value(&mut self) {
        self.value.clear();
    }

    // Param is passed by value, moved
    pub fn set_value(&mut self, v: ::std::string::String) {
        self.value = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_value(&mut self) -> &mut ::std::string::String {
        &mut self.value
    }

    // Take field
    pub fn take_value(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.value, ::std::string::String::new())
    }

    pub fn get_value(&self) -> &str {
        &self.value
    }

    // .kvrpcpb.RespErr err = 2;

    pub fn clear_err(&mut self) {
        self.err = RespErr::OK;
    }

    // Param is passed by value, moved
    pub fn set_err(&mut self, v: RespErr) {
        self.err = v;
    }

    pub fn get_err(&self) -> RespErr {
        self.err
    }
}

impl ::protobuf::Message for GetResp {
    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.value)?;
                },
                2 => {
                    if wire_type == ::protobuf::wire_format::WireTypeVarint {self.err = is.read_enum()?;} else { return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type)); }
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if !self.value.is_empty() {
            my_size += ::protobuf::rt::string_size(1, &self.value);
        }
        if self.err != RespErr::OK {
            my_size += ::protobuf::rt::enum_size(2, self.err);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream) -> ::protobuf::ProtobufResult<()> {
        if !self.value.is_empty() {
            os.write_string(1, &self.value)?;
        }
        if self.err != RespErr::OK {
            os.write_enum(2, self.err.value())?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &::std::any::Any {
        self as &::std::any::Any
    }
    fn as_any_mut(&mut self) -> &mut ::std::any::Any {
        self as &mut ::std::any::Any
    }
    fn into_any(self: Box<Self>) -> ::std::boxed::Box<::std::any::Any> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> GetResp {
        GetResp::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static mut descriptor: ::protobuf::lazy::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const ::protobuf::reflect::MessageDescriptor,
        };
        unsafe {
            descriptor.get(|| {
                let mut fields = ::std::vec::Vec::new();
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                    "value",
                    |m: &GetResp| { &m.value },
                    |m: &mut GetResp| { &mut m.value },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeEnum<RespErr>>(
                    "err",
                    |m: &GetResp| { &m.err },
                    |m: &mut GetResp| { &mut m.err },
                ));
                ::protobuf::reflect::MessageDescriptor::new::<GetResp>(
                    "GetResp",
                    fields,
                    file_descriptor_proto()
                )
            })
        }
    }

    fn default_instance() -> &'static GetResp {
        static mut instance: ::protobuf::lazy::Lazy<GetResp> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const GetResp,
        };
        unsafe {
            instance.get(GetResp::new)
        }
    }
}

impl ::protobuf::Clear for GetResp {
    fn clear(&mut self) {
        self.clear_value();
        self.clear_err();
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for GetResp {
    fn fmt(&self, f: &mut ::std::fmt::Formatter) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for GetResp {
    fn as_ref(&self) -> ::protobuf::reflect::ProtobufValueRef {
        ::protobuf::reflect::ProtobufValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
pub struct PutResp {
    // message fields
    pub err: RespErr,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl PutResp {
    pub fn new() -> PutResp {
        ::std::default::Default::default()
    }

    // .kvrpcpb.RespErr err = 1;

    pub fn clear_err(&mut self) {
        self.err = RespErr::OK;
    }

    // Param is passed by value, moved
    pub fn set_err(&mut self, v: RespErr) {
        self.err = v;
    }

    pub fn get_err(&self) -> RespErr {
        self.err
    }
}

impl ::protobuf::Message for PutResp {
    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    if wire_type == ::protobuf::wire_format::WireTypeVarint {self.err = is.read_enum()?;} else { return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type)); }
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if self.err != RespErr::OK {
            my_size += ::protobuf::rt::enum_size(1, self.err);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream) -> ::protobuf::ProtobufResult<()> {
        if self.err != RespErr::OK {
            os.write_enum(1, self.err.value())?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &::std::any::Any {
        self as &::std::any::Any
    }
    fn as_any_mut(&mut self) -> &mut ::std::any::Any {
        self as &mut ::std::any::Any
    }
    fn into_any(self: Box<Self>) -> ::std::boxed::Box<::std::any::Any> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> PutResp {
        PutResp::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static mut descriptor: ::protobuf::lazy::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const ::protobuf::reflect::MessageDescriptor,
        };
        unsafe {
            descriptor.get(|| {
                let mut fields = ::std::vec::Vec::new();
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeEnum<RespErr>>(
                    "err",
                    |m: &PutResp| { &m.err },
                    |m: &mut PutResp| { &mut m.err },
                ));
                ::protobuf::reflect::MessageDescriptor::new::<PutResp>(
                    "PutResp",
                    fields,
                    file_descriptor_proto()
                )
            })
        }
    }

    fn default_instance() -> &'static PutResp {
        static mut instance: ::protobuf::lazy::Lazy<PutResp> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const PutResp,
        };
        unsafe {
            instance.get(PutResp::new)
        }
    }
}

impl ::protobuf::Clear for PutResp {
    fn clear(&mut self) {
        self.clear_err();
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for PutResp {
    fn fmt(&self, f: &mut ::std::fmt::Formatter) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for PutResp {
    fn as_ref(&self) -> ::protobuf::reflect::ProtobufValueRef {
        ::protobuf::reflect::ProtobufValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
pub struct DeleteResp {
    // message fields
    pub err: RespErr,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl DeleteResp {
    pub fn new() -> DeleteResp {
        ::std::default::Default::default()
    }

    // .kvrpcpb.RespErr err = 1;

    pub fn clear_err(&mut self) {
        self.err = RespErr::OK;
    }

    // Param is passed by value, moved
    pub fn set_err(&mut self, v: RespErr) {
        self.err = v;
    }

    pub fn get_err(&self) -> RespErr {
        self.err
    }
}

impl ::protobuf::Message for DeleteResp {
    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    if wire_type == ::protobuf::wire_format::WireTypeVarint {self.err = is.read_enum()?;} else { return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type)); }
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if self.err != RespErr::OK {
            my_size += ::protobuf::rt::enum_size(1, self.err);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream) -> ::protobuf::ProtobufResult<()> {
        if self.err != RespErr::OK {
            os.write_enum(1, self.err.value())?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &::std::any::Any {
        self as &::std::any::Any
    }
    fn as_any_mut(&mut self) -> &mut ::std::any::Any {
        self as &mut ::std::any::Any
    }
    fn into_any(self: Box<Self>) -> ::std::boxed::Box<::std::any::Any> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> DeleteResp {
        DeleteResp::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static mut descriptor: ::protobuf::lazy::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const ::protobuf::reflect::MessageDescriptor,
        };
        unsafe {
            descriptor.get(|| {
                let mut fields = ::std::vec::Vec::new();
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeEnum<RespErr>>(
                    "err",
                    |m: &DeleteResp| { &m.err },
                    |m: &mut DeleteResp| { &mut m.err },
                ));
                ::protobuf::reflect::MessageDescriptor::new::<DeleteResp>(
                    "DeleteResp",
                    fields,
                    file_descriptor_proto()
                )
            })
        }
    }

    fn default_instance() -> &'static DeleteResp {
        static mut instance: ::protobuf::lazy::Lazy<DeleteResp> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const DeleteResp,
        };
        unsafe {
            instance.get(DeleteResp::new)
        }
    }
}

impl ::protobuf::Clear for DeleteResp {
    fn clear(&mut self) {
        self.clear_err();
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for DeleteResp {
    fn fmt(&self, f: &mut ::std::fmt::Formatter) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for DeleteResp {
    fn as_ref(&self) -> ::protobuf::reflect::ProtobufValueRef {
        ::protobuf::reflect::ProtobufValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
pub struct RaftDone {
    // message fields
    pub err: RespErr,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl RaftDone {
    pub fn new() -> RaftDone {
        ::std::default::Default::default()
    }

    // .kvrpcpb.RespErr err = 1;

    pub fn clear_err(&mut self) {
        self.err = RespErr::OK;
    }

    // Param is passed by value, moved
    pub fn set_err(&mut self, v: RespErr) {
        self.err = v;
    }

    pub fn get_err(&self) -> RespErr {
        self.err
    }
}

impl ::protobuf::Message for RaftDone {
    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    if wire_type == ::protobuf::wire_format::WireTypeVarint {self.err = is.read_enum()?;} else { return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type)); }
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if self.err != RespErr::OK {
            my_size += ::protobuf::rt::enum_size(1, self.err);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream) -> ::protobuf::ProtobufResult<()> {
        if self.err != RespErr::OK {
            os.write_enum(1, self.err.value())?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &::std::any::Any {
        self as &::std::any::Any
    }
    fn as_any_mut(&mut self) -> &mut ::std::any::Any {
        self as &mut ::std::any::Any
    }
    fn into_any(self: Box<Self>) -> ::std::boxed::Box<::std::any::Any> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> RaftDone {
        RaftDone::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static mut descriptor: ::protobuf::lazy::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const ::protobuf::reflect::MessageDescriptor,
        };
        unsafe {
            descriptor.get(|| {
                let mut fields = ::std::vec::Vec::new();
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeEnum<RespErr>>(
                    "err",
                    |m: &RaftDone| { &m.err },
                    |m: &mut RaftDone| { &mut m.err },
                ));
                ::protobuf::reflect::MessageDescriptor::new::<RaftDone>(
                    "RaftDone",
                    fields,
                    file_descriptor_proto()
                )
            })
        }
    }

    fn default_instance() -> &'static RaftDone {
        static mut instance: ::protobuf::lazy::Lazy<RaftDone> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const RaftDone,
        };
        unsafe {
            instance.get(RaftDone::new)
        }
    }
}

impl ::protobuf::Clear for RaftDone {
    fn clear(&mut self) {
        self.clear_err();
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for RaftDone {
    fn fmt(&self, f: &mut ::std::fmt::Formatter) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for RaftDone {
    fn as_ref(&self) -> ::protobuf::reflect::ProtobufValueRef {
        ::protobuf::reflect::ProtobufValueRef::Message(self)
    }
}

#[derive(Clone,PartialEq,Eq,Debug,Hash)]
pub enum RespErr {
    OK = 0,
    ErrWrongLeader = 1,
    ErrNoKey = 2,
}

impl ::protobuf::ProtobufEnum for RespErr {
    fn value(&self) -> i32 {
        *self as i32
    }

    fn from_i32(value: i32) -> ::std::option::Option<RespErr> {
        match value {
            0 => ::std::option::Option::Some(RespErr::OK),
            1 => ::std::option::Option::Some(RespErr::ErrWrongLeader),
            2 => ::std::option::Option::Some(RespErr::ErrNoKey),
            _ => ::std::option::Option::None
        }
    }

    fn values() -> &'static [Self] {
        static values: &'static [RespErr] = &[
            RespErr::OK,
            RespErr::ErrWrongLeader,
            RespErr::ErrNoKey,
        ];
        values
    }

    fn enum_descriptor_static() -> &'static ::protobuf::reflect::EnumDescriptor {
        static mut descriptor: ::protobuf::lazy::Lazy<::protobuf::reflect::EnumDescriptor> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const ::protobuf::reflect::EnumDescriptor,
        };
        unsafe {
            descriptor.get(|| {
                ::protobuf::reflect::EnumDescriptor::new("RespErr", file_descriptor_proto())
            })
        }
    }
}

impl ::std::marker::Copy for RespErr {
}

impl ::std::default::Default for RespErr {
    fn default() -> Self {
        RespErr::OK
    }
}

impl ::protobuf::reflect::ProtobufValue for RespErr {
    fn as_ref(&self) -> ::protobuf::reflect::ProtobufValueRef {
        ::protobuf::reflect::ProtobufValueRef::Enum(self.descriptor())
    }
}

#[derive(Clone,PartialEq,Eq,Debug,Hash)]
pub enum ReqType {
    Get = 0,
    Put = 1,
    Delete = 2,
    PeerAddr = 3,
}

impl ::protobuf::ProtobufEnum for ReqType {
    fn value(&self) -> i32 {
        *self as i32
    }

    fn from_i32(value: i32) -> ::std::option::Option<ReqType> {
        match value {
            0 => ::std::option::Option::Some(ReqType::Get),
            1 => ::std::option::Option::Some(ReqType::Put),
            2 => ::std::option::Option::Some(ReqType::Delete),
            3 => ::std::option::Option::Some(ReqType::PeerAddr),
            _ => ::std::option::Option::None
        }
    }

    fn values() -> &'static [Self] {
        static values: &'static [ReqType] = &[
            ReqType::Get,
            ReqType::Put,
            ReqType::Delete,
            ReqType::PeerAddr,
        ];
        values
    }

    fn enum_descriptor_static() -> &'static ::protobuf::reflect::EnumDescriptor {
        static mut descriptor: ::protobuf::lazy::Lazy<::protobuf::reflect::EnumDescriptor> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const ::protobuf::reflect::EnumDescriptor,
        };
        unsafe {
            descriptor.get(|| {
                ::protobuf::reflect::EnumDescriptor::new("ReqType", file_descriptor_proto())
            })
        }
    }
}

impl ::std::marker::Copy for ReqType {
}

impl ::std::default::Default for ReqType {
    fn default() -> Self {
        ReqType::Get
    }
}

impl ::protobuf::reflect::ProtobufValue for ReqType {
    fn as_ref(&self) -> ::protobuf::reflect::ProtobufValueRef {
        ::protobuf::reflect::ProtobufValueRef::Enum(self.descriptor())
    }
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\rkvrpcpb.proto\x12\x07kvrpcpb\x1a\reraftpb.proto\"\xc1\x01\n\x05KvReq\
    \x12\x10\n\x03key\x18\x01\x20\x01(\tR\x03key\x12\x14\n\x05value\x18\x02\
    \x20\x01(\tR\x05value\x12\x1b\n\tclient_id\x18\x03\x20\x01(\x04R\x08clie\
    ntId\x12\x10\n\x03seq\x18\x04\x20\x01(\x04R\x03seq\x12+\n\x08req_type\
    \x18\x05\x20\x01(\x0e2\x10.kvrpcpb.ReqTypeR\x07reqType\x12\x17\n\x07peer\
    _id\x18\x06\x20\x01(\x04R\x06peerId\x12\x1b\n\tpeer_addr\x18\x07\x20\x01\
    (\tR\x08peerAddr\"X\n\rConfChangeReq\x12#\n\x02cc\x18\x01\x20\x01(\x0b2\
    \x13.eraftpb.ConfChangeR\x02cc\x12\x0e\n\x02ip\x18\x02\x20\x01(\tR\x02ip\
    \x12\x12\n\x04port\x18\x03\x20\x01(\rR\x04port\"C\n\x07GetResp\x12\x14\n\
    \x05value\x18\x01\x20\x01(\tR\x05value\x12\"\n\x03err\x18\x02\x20\x01(\
    \x0e2\x10.kvrpcpb.RespErrR\x03err\"-\n\x07PutResp\x12\"\n\x03err\x18\x01\
    \x20\x01(\x0e2\x10.kvrpcpb.RespErrR\x03err\"0\n\nDeleteResp\x12\"\n\x03e\
    rr\x18\x01\x20\x01(\x0e2\x10.kvrpcpb.RespErrR\x03err\".\n\x08RaftDone\
    \x12\"\n\x03err\x18\x01\x20\x01(\x0e2\x10.kvrpcpb.RespErrR\x03err*3\n\
    \x07RespErr\x12\x06\n\x02OK\x10\0\x12\x12\n\x0eErrWrongLeader\x10\x01\
    \x12\x0c\n\x08ErrNoKey\x10\x02*5\n\x07ReqType\x12\x07\n\x03Get\x10\0\x12\
    \x07\n\x03Put\x10\x01\x12\n\n\x06Delete\x10\x02\x12\x0c\n\x08PeerAddr\
    \x10\x03J\xa0\x0c\n\x06\x12\x04\0\01\x01\n\x08\n\x01\x0c\x12\x03\0\0\x12\
    \n\x08\n\x01\x02\x12\x03\x01\x08\x0f\n\t\n\x02\x03\0\x12\x03\x03\x07\x16\
    \n\n\n\x02\x05\0\x12\x04\x05\0\t\x01\n\n\n\x03\x05\0\x01\x12\x03\x05\x05\
    \x0c\n\x0b\n\x04\x05\0\x02\0\x12\x03\x06\x02\t\n\x0c\n\x05\x05\0\x02\0\
    \x01\x12\x03\x06\x02\x04\n\x0c\n\x05\x05\0\x02\0\x02\x12\x03\x06\x07\x08\
    \n\x0b\n\x04\x05\0\x02\x01\x12\x03\x07\x02\x15\n\x0c\n\x05\x05\0\x02\x01\
    \x01\x12\x03\x07\x02\x10\n\x0c\n\x05\x05\0\x02\x01\x02\x12\x03\x07\x13\
    \x14\n\x0b\n\x04\x05\0\x02\x02\x12\x03\x08\x02\x0f\n\x0c\n\x05\x05\0\x02\
    \x02\x01\x12\x03\x08\x02\n\n\x0c\n\x05\x05\0\x02\x02\x02\x12\x03\x08\r\
    \x0e\n\n\n\x02\x05\x01\x12\x04\x0b\0\x10\x01\n\n\n\x03\x05\x01\x01\x12\
    \x03\x0b\x05\x0c\n\x0b\n\x04\x05\x01\x02\0\x12\x03\x0c\x02\n\n\x0c\n\x05\
    \x05\x01\x02\0\x01\x12\x03\x0c\x02\x05\n\x0c\n\x05\x05\x01\x02\0\x02\x12\
    \x03\x0c\x08\t\n\x0b\n\x04\x05\x01\x02\x01\x12\x03\r\x02\n\n\x0c\n\x05\
    \x05\x01\x02\x01\x01\x12\x03\r\x02\x05\n\x0c\n\x05\x05\x01\x02\x01\x02\
    \x12\x03\r\x08\t\n\x0b\n\x04\x05\x01\x02\x02\x12\x03\x0e\x02\r\n\x0c\n\
    \x05\x05\x01\x02\x02\x01\x12\x03\x0e\x02\x08\n\x0c\n\x05\x05\x01\x02\x02\
    \x02\x12\x03\x0e\x0b\x0c\n\x0b\n\x04\x05\x01\x02\x03\x12\x03\x0f\x02\x0f\
    \n\x0c\n\x05\x05\x01\x02\x03\x01\x12\x03\x0f\x02\n\n\x0c\n\x05\x05\x01\
    \x02\x03\x02\x12\x03\x0f\r\x0e\n\n\n\x02\x04\0\x12\x04\x12\0\x1a\x01\n\n\
    \n\x03\x04\0\x01\x12\x03\x12\x08\r\n\x0b\n\x04\x04\0\x02\0\x12\x03\x13\
    \x02\x11\n\r\n\x05\x04\0\x02\0\x04\x12\x04\x13\x02\x12\x0f\n\x0c\n\x05\
    \x04\0\x02\0\x05\x12\x03\x13\x02\x08\n\x0c\n\x05\x04\0\x02\0\x01\x12\x03\
    \x13\t\x0c\n\x0c\n\x05\x04\0\x02\0\x03\x12\x03\x13\x0f\x10\n\x0b\n\x04\
    \x04\0\x02\x01\x12\x03\x14\x02\x13\n\r\n\x05\x04\0\x02\x01\x04\x12\x04\
    \x14\x02\x13\x11\n\x0c\n\x05\x04\0\x02\x01\x05\x12\x03\x14\x02\x08\n\x0c\
    \n\x05\x04\0\x02\x01\x01\x12\x03\x14\t\x0e\n\x0c\n\x05\x04\0\x02\x01\x03\
    \x12\x03\x14\x11\x12\n\x0b\n\x04\x04\0\x02\x02\x12\x03\x15\x02\x17\n\r\n\
    \x05\x04\0\x02\x02\x04\x12\x04\x15\x02\x14\x13\n\x0c\n\x05\x04\0\x02\x02\
    \x05\x12\x03\x15\x02\x08\n\x0c\n\x05\x04\0\x02\x02\x01\x12\x03\x15\t\x12\
    \n\x0c\n\x05\x04\0\x02\x02\x03\x12\x03\x15\x15\x16\n\x0b\n\x04\x04\0\x02\
    \x03\x12\x03\x16\x02\x11\n\r\n\x05\x04\0\x02\x03\x04\x12\x04\x16\x02\x15\
    \x17\n\x0c\n\x05\x04\0\x02\x03\x05\x12\x03\x16\x02\x08\n\x0c\n\x05\x04\0\
    \x02\x03\x01\x12\x03\x16\t\x0c\n\x0c\n\x05\x04\0\x02\x03\x03\x12\x03\x16\
    \x0f\x10\n\x0b\n\x04\x04\0\x02\x04\x12\x03\x17\x02\x17\n\r\n\x05\x04\0\
    \x02\x04\x04\x12\x04\x17\x02\x16\x11\n\x0c\n\x05\x04\0\x02\x04\x06\x12\
    \x03\x17\x02\t\n\x0c\n\x05\x04\0\x02\x04\x01\x12\x03\x17\n\x12\n\x0c\n\
    \x05\x04\0\x02\x04\x03\x12\x03\x17\x15\x16\n\x0b\n\x04\x04\0\x02\x05\x12\
    \x03\x18\x02\x15\n\r\n\x05\x04\0\x02\x05\x04\x12\x04\x18\x02\x17\x17\n\
    \x0c\n\x05\x04\0\x02\x05\x05\x12\x03\x18\x02\x08\n\x0c\n\x05\x04\0\x02\
    \x05\x01\x12\x03\x18\t\x10\n\x0c\n\x05\x04\0\x02\x05\x03\x12\x03\x18\x13\
    \x14\n\x0b\n\x04\x04\0\x02\x06\x12\x03\x19\x02\x17\n\r\n\x05\x04\0\x02\
    \x06\x04\x12\x04\x19\x02\x18\x15\n\x0c\n\x05\x04\0\x02\x06\x05\x12\x03\
    \x19\x02\x08\n\x0c\n\x05\x04\0\x02\x06\x01\x12\x03\x19\t\x12\n\x0c\n\x05\
    \x04\0\x02\x06\x03\x12\x03\x19\x15\x16\n\n\n\x02\x04\x01\x12\x04\x1c\0\
    \x20\x01\n\n\n\x03\x04\x01\x01\x12\x03\x1c\x08\x15\n\x0b\n\x04\x04\x01\
    \x02\0\x12\x03\x1d\x02\x1c\n\r\n\x05\x04\x01\x02\0\x04\x12\x04\x1d\x02\
    \x1c\x17\n\x0c\n\x05\x04\x01\x02\0\x06\x12\x03\x1d\x02\x14\n\x0c\n\x05\
    \x04\x01\x02\0\x01\x12\x03\x1d\x15\x17\n\x0c\n\x05\x04\x01\x02\0\x03\x12\
    \x03\x1d\x1a\x1b\n\x0b\n\x04\x04\x01\x02\x01\x12\x03\x1e\x02\x10\n\r\n\
    \x05\x04\x01\x02\x01\x04\x12\x04\x1e\x02\x1d\x1c\n\x0c\n\x05\x04\x01\x02\
    \x01\x05\x12\x03\x1e\x02\x08\n\x0c\n\x05\x04\x01\x02\x01\x01\x12\x03\x1e\
    \t\x0b\n\x0c\n\x05\x04\x01\x02\x01\x03\x12\x03\x1e\x0e\x0f\n\x0b\n\x04\
    \x04\x01\x02\x02\x12\x03\x1f\x02\x12\n\r\n\x05\x04\x01\x02\x02\x04\x12\
    \x04\x1f\x02\x1e\x10\n\x0c\n\x05\x04\x01\x02\x02\x05\x12\x03\x1f\x02\x08\
    \n\x0c\n\x05\x04\x01\x02\x02\x01\x12\x03\x1f\t\r\n\x0c\n\x05\x04\x01\x02\
    \x02\x03\x12\x03\x1f\x10\x11\n\n\n\x02\x04\x02\x12\x04\"\0%\x01\n\n\n\
    \x03\x04\x02\x01\x12\x03\"\x08\x0f\n\x0b\n\x04\x04\x02\x02\0\x12\x03#\
    \x02\x13\n\r\n\x05\x04\x02\x02\0\x04\x12\x04#\x02\"\x11\n\x0c\n\x05\x04\
    \x02\x02\0\x05\x12\x03#\x02\x08\n\x0c\n\x05\x04\x02\x02\0\x01\x12\x03#\t\
    \x0e\n\x0c\n\x05\x04\x02\x02\0\x03\x12\x03#\x11\x12\n\x0b\n\x04\x04\x02\
    \x02\x01\x12\x03$\x02\x12\n\r\n\x05\x04\x02\x02\x01\x04\x12\x04$\x02#\
    \x13\n\x0c\n\x05\x04\x02\x02\x01\x06\x12\x03$\x02\t\n\x0c\n\x05\x04\x02\
    \x02\x01\x01\x12\x03$\n\r\n\x0c\n\x05\x04\x02\x02\x01\x03\x12\x03$\x10\
    \x11\n\n\n\x02\x04\x03\x12\x04'\0)\x01\n\n\n\x03\x04\x03\x01\x12\x03'\
    \x08\x0f\n\x0b\n\x04\x04\x03\x02\0\x12\x03(\x02\x12\n\r\n\x05\x04\x03\
    \x02\0\x04\x12\x04(\x02'\x11\n\x0c\n\x05\x04\x03\x02\0\x06\x12\x03(\x02\
    \t\n\x0c\n\x05\x04\x03\x02\0\x01\x12\x03(\n\r\n\x0c\n\x05\x04\x03\x02\0\
    \x03\x12\x03(\x10\x11\n\n\n\x02\x04\x04\x12\x04+\0-\x01\n\n\n\x03\x04\
    \x04\x01\x12\x03+\x08\x12\n\x0b\n\x04\x04\x04\x02\0\x12\x03,\x02\x12\n\r\
    \n\x05\x04\x04\x02\0\x04\x12\x04,\x02+\x14\n\x0c\n\x05\x04\x04\x02\0\x06\
    \x12\x03,\x02\t\n\x0c\n\x05\x04\x04\x02\0\x01\x12\x03,\n\r\n\x0c\n\x05\
    \x04\x04\x02\0\x03\x12\x03,\x10\x11\n\n\n\x02\x04\x05\x12\x04/\01\x01\n\
    \n\n\x03\x04\x05\x01\x12\x03/\x08\x10\n\x0b\n\x04\x04\x05\x02\0\x12\x030\
    \x02\x12\n\r\n\x05\x04\x05\x02\0\x04\x12\x040\x02/\x12\n\x0c\n\x05\x04\
    \x05\x02\0\x06\x12\x030\x02\t\n\x0c\n\x05\x04\x05\x02\0\x01\x12\x030\n\r\
    \n\x0c\n\x05\x04\x05\x02\0\x03\x12\x030\x10\x11b\x06proto3\
";

static mut file_descriptor_proto_lazy: ::protobuf::lazy::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::lazy::Lazy {
    lock: ::protobuf::lazy::ONCE_INIT,
    ptr: 0 as *const ::protobuf::descriptor::FileDescriptorProto,
};

fn parse_descriptor_proto() -> ::protobuf::descriptor::FileDescriptorProto {
    ::protobuf::parse_from_bytes(file_descriptor_proto_data).unwrap()
}

pub fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    unsafe {
        file_descriptor_proto_lazy.get(|| {
            parse_descriptor_proto()
        })
    }
}
